# Generated by Django 6.0.1 on 2026-02-02 08:44

import orders.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_id', models.CharField(default=orders.models.generate_ticket_id, editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_type', models.CharField(choices=[('DL', 'Drivers License'), ('VEHICLE', 'Vehicle Renewal'), ('NEW_PLATE', 'New Number Plate')], max_length=20)),
                ('vehicle_details', models.TextField(blank=True, help_text='Car Model, Year, Plate Number', null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('COMPLETED', 'Completed')], default='RECEIVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
