# Generated by Django 6.0.1 on 2026-02-03 02:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('state_of_practice', models.CharField(max_length=100)),
                ('is_licensed', models.BooleanField(default=False)),
                ('services_offered', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('residential_address', models.TextField()),
                ('dob', models.DateField()),
                ('state_of_origin', models.CharField(max_length=100)),
                ('lga_of_origin', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='Nigerian', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('service_type', models.CharField(choices=[('DL', 'Drivers License'), ('VEHICLE', 'Vehicle Papers'), ('INSPECTION', 'Car Inspection')], max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received (Payment Processing)'), ('VIO', 'Processing at VIO'), ('MVAA', 'Processing at MVAA'), ('READY', 'Ready for Delivery'), ('DELIVERED', 'Delivered')], default='RECEIVED', max_length=20)),
                ('dl_application_type', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('genotype', models.CharField(blank=True, max_length=5, null=True)),
                ('passport_photo', models.FileField(blank=True, null=True, upload_to='passports/')),
                ('nin_slip', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('vehicle_paper_types', models.JSONField(blank=True, default=list, null=True)),
                ('vehicle_transaction_type', models.CharField(blank=True, max_length=50, null=True)),
                ('existing_documents_desc', models.TextField(blank=True, null=True)),
                ('vehicle_details', models.TextField(blank=True, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=100, null=True)),
                ('inspection_type', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_inspection_date', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=20, null=True)),
                ('fee_acknowledged', models.BooleanField(default=False)),
                ('signature_authorized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='supporting_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
        ),
    ]
